#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
CYAN="\e[36m"
ENDCOLOR="\e[0m"

pub_ip=$(wget -qO- https://ipecho.net/plain ; echo)

old_db_port=$(grep "DROPBEAR_PORT=" /etc/default/dropbear | sed 's/=/= /'  | awk '{print$2}')

old_db_ssl=$(grep "accept =" /etc/stunnel/stunnel.conf | sed ':a;N;$!ba;s/\n/ /g' | sed 's/accept =//g' | awk '{print$1}')

old_op_ssl=$(grep "accept =" /etc/stunnel/stunnel.conf | sed ':a;N;$!ba;s/\n/ /g' | sed 's/accept =//g' | awk '{print$2}')

old_squid_port=$(sed /^#/d /etc/squid/squid.conf | grep "http_port" | awk '{print$2}')

old_udpgw_port=$(cat /etc/systemd/system/udpgw.service | sed 's/ /\n/g'  | grep "127.0.0.1:" | sed 's/:/ /' | awk '{print$2}')

if ! [ $(id -u) = 0 ]; then
   echo -e "${RED}Plese run the command with root privilages!${ENDCOLOR}"
   exit 1
fi
 
clear

echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m      💎𝐃𝐀𝐓𝐀𝐊𝐈𝐍𝐆𝐃𝐎𝐌-𝐀𝐔𝐓𝐎-𝐒𝐒𝐇-𝐒𝐂𝐑𝐈𝐏𝐓💎\E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo "" 
echo -e "${RED} 🛑 𝚂𝙲𝚁𝙸𝙿𝚃 𝙱𝚈⚡️DATA-KING-OFFCIAL⚡️\n"                                    
echo -e "${GREEN} 🛑 𝚄𝙿𝙳𝙰𝚃𝙴 𝚅𝙴𝚁𝚂𝙸𝙾𝙽 - 1\n"
echo -e "${BLUE} 🛑 Telegram - @Dk_king_offcial\n"   
echo -e "${YELLOW} 🛑 Whatsapp - wa.me/+94768100942\n"          
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
echo -e "${YELLOW}------------------ ⭐️Server Details⭐️ ----------------------\n"
echo -e "${GREEN}⭐️YOUR SERVER IP ADDRESS : $pub_ip"
echo -e "⭐️Dropbear port : $old_db_port"
echo -e "⭐️SSL port : $old_db_ssl"
echo -e "⭐️Openssh +  SSL port : $old_op_ssl"
echo -e "⭐️Squid port : $old_squid_port"
echo -e "⭐️BadVPN  port : $old_udpgw_port\n"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
echo -e "${CYAN}📌1)🚥Add new users"
echo -e "📌2)🚥View All users"
echo -e "📌3)🚥Edit an existing user"
echo -e "📌4)🚥Delete a user"
echo -e "📌5)🚥Change Ports"
echo -e "📌6)🚥Edit SSH Banner"
echo -e "📌7)🚥Server Information"
echo -e "📌8)🚥Server Speedtest"
echo -e "📌9)🚥Remove Script"
echo -e "📌10)🚥Exit"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━•ᴅᴀᴛᴀᴋɪɴɢᴅᴏᴍ ᴘʀᴏᴊᴇᴄᴛ•━━━━━━━━━━━━━━━━━━━━\n"

case $n in
  1) /etc/elhssh-v2/UserManager.sh;;
  2) /etc/elhssh-v2/ListUsers.sh;;
  3) /etc/elhssh-v2/ChangeUser.sh;;
  4) /etc/elhssh-v2/DelUser.sh;;
  5) /etc/elhssh-v2/ChangePorts.sh;;
  6) /etc/elhssh-v2/Banner.sh;;
  7) clear && screenfetch -p || echo -e "${RED}Screenfetch not installed. please install${ENDCOLOR}"; echo -e "\nPress Enter to return back to the menu";read;menu;;  
  8) clear && python3 /etc/elhssh-v2/speedtest-cli || echo -e "${RED}Python3 or speedtest-cli not installed. please install${ENDCOLOR}"; echo -e "\nPress Enter to return back to the menu";read;menu;;
  9) /etc/elhssh-v2/RemoveScript.sh;;
  10) clear;exit;;
  *) echo -e "${RED}\nInvalid Option. Press Enter to return back to the menu${ENDCOLOR}";read && menu;;
esac
